apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ .Values.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: hytale-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: UDP
              name: game-udp
          env:
            - name: JAVA_OPTIONS
              value: {{ .Values.jvm.additionalOptions | join " " }}
          volumeMounts:
            - name: {{ .Values.name }}
              mountPath: /opt/hytale
            - name: logs-storage
              mountPath: /opt/hytale/logs
            - name: credentials-volume
              mountPath: /opt/hytale-downloader-secret
              subPath: .hytale-downloader-credentials.json
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}          
          startupProbe:
            exec:
              command:
                - cat
                - {{ .Values.probes.startup.file }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
      volumes:
        - name: logs-storage
          emptyDir: {}
        - name: credentials-volume
          secret:
            secretName: {{ .Values.credentials.secretName }}
            items:
              - key: {{ .Values.credentials.credentialsKey }}
                path: credentials
            optional: true
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.name }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}

